# Reading Files

In [31]:
import pandas as pd

In [32]:
df = pd.read_csv(r"countries of the world.csv")
df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
..               ...                                  ...
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [33]:
#df = pd.read_csv(r"C:\Users\alexf\OneDrive\Documents\Pandas Tutorial\countries of the world.txt", sep = '\t')
#df

df = pd.read_table(r"countries of the world.csv", sep = ',')
df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
..               ...                                  ...
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [34]:
df = pd.read_json(r"json_sample.json")
df

,12 Strong,A Fantastic Woman (Una Mujer Fantástica),All The Money In The World,Bilal: A New Breed Of Hero,...,The Shape Of Water,"Three Billboards Outside Ebbing, Missouri",Till The End Of The World,Winchester
0,"{'Genre': 'Action', 'Gross': '$453,173', 'IMDB...","{'popcornscore': 83, 'rating': 'R', 'tomatosco...","{'popcornscore': 71, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG13', 'tomato...",...,"{'Genre': 'Adventure', 'Gross': '$448,287', 'I...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': -1, 'rating': 'NR', 'tomatosc...","{'Genre': 'Biography', 'Gross': '$696,786', 'I..."

In [35]:
df2 = pd.read_excel(r"world_population_excel_workbook.xlsx", sheet_name = 'Sheet1')
df2

     Rank CCA3         Country    Capital
0      36  AFG     Afghanistan      Kabul
1     138  ALB         Albania     Tirana
2      34  DZA         Algeria    Algiers
3     213  ASM  American Samoa  Pago Pago
..    ...  ...             ...        ...
230   172  ESH  Western Sahara  El AaiÃºn
231    46  YEM           Yemen      Sanaa
232    63  ZMB          Zambia     Lusaka
233    74  ZWE        Zimbabwe     Harare

[234 rows x 4 columns]

In [36]:
pd.set_option('display.max.rows', 8)
pd.set_option('display.max.columns', 8)

In [37]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     234 non-null    int64
 1   CCA3     234 non-null    str
 2   Country  234 non-null    str
 3   Capital  234 non-null    str
dtypes: int64(1), str(3)
memory usage: 12.1 KB

In [38]:
df2

     Rank CCA3         Country    Capital
0      36  AFG     Afghanistan      Kabul
1     138  ALB         Albania     Tirana
2      34  DZA         Algeria    Algiers
3     213  ASM  American Samoa  Pago Pago
..    ...  ...             ...        ...
230   172  ESH  Western Sahara  El AaiÃºn
231    46  YEM           Yemen      Sanaa
232    63  ZMB          Zambia     Lusaka
233    74  ZWE        Zimbabwe     Harare

[234 rows x 4 columns]

In [43]:
df2.shape

(234, 4)

In [44]:
df2.tail(10)

     Rank CCA3         Country       Capital
224    43  UZB      Uzbekistan      Tashkent
225   181  VUT         Vanuatu     Port-Vila
226   234  VAT    Vatican City  Vatican City
227    51  VEN       Venezuela       Caracas
..    ...  ...             ...           ...
230   172  ESH  Western Sahara     El AaiÃºn
231    46  YEM           Yemen         Sanaa
232    63  ZMB          Zambia        Lusaka
233    74  ZWE        Zimbabwe        Harare

[10 rows x 4 columns]

In [45]:
df2.head(10)

    Rank CCA3              Country         Capital
0     36  AFG          Afghanistan           Kabul
1    138  ALB              Albania          Tirana
2     34  DZA              Algeria         Algiers
3    213  ASM       American Samoa       Pago Pago
..   ...  ...                  ...             ...
6    224  AIA             Anguilla      The Valley
7    201  ATG  Antigua and Barbuda  Saint Johnâ€™s
8     33  ARG            Argentina    Buenos Aires
9    140  ARM              Armenia         Yerevan

[10 rows x 4 columns]

In [46]:
df2['Rank']

0       36
1      138
2       34
3      213
      ...
230    172
231     46
232     63
233     74
Name: Rank, Length: 234, dtype: int64

In [47]:
df2.columns

Index(['Rank', 'CCA3', 'Country', 'Capital'], dtype='str')

In [60]:
df2[df2['Country'] == 'Uzbekistan']         # df2['Country' is boolean indexing

     Rank CCA3     Country   Capital
224    43  UZB  Uzbekistan  Tashkent

In [61]:
df2.loc[df2['Country'] == 'Uzbekistan']                  # same as above

     Rank CCA3     Country   Capital
224    43  UZB  Uzbekistan  Tashkent

**loc** - label based indexing,

**iloc** - integer based indexing

In [62]:
df2.iloc[224]        # iloc displaying row at index 224

Rank               43
CCA3              UZB
Country    Uzbekistan
Capital      Tashkent
Name: 224, dtype: object

In [63]:
# Filters for Uzbekistan and returns only the Capital and Rank columns
df2.loc[df2['Country'] == 'Uzbekistan', ['Capital', 'Rank']]

      Capital  Rank
224  Tashkent    43